select 'GRANT SELECT, INSERT, UPDATE, DELETE ON '|| schemaname||'.'||tablename || ' TO zago;'  
from pg_tables where schemaname = 'public'


GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_lltm TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.terreno_sujeito_inundacao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.terreno_exposto TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.terreno_cartorial TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.elemento_fisiografico_natural_l TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.elemento_fisiografico_natural_p TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.elemento_fisiografico_p TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pais TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.geometria_observacao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.spatial_ref_sys TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.elemento_fisiografico_natural_a TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_terreno_marginal TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_terreno_acrescido_marinha TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.delimitacao_fisica TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.estrut_apoio_transporte_l TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.mar_territorial TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.municipio TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.utilizacao_p TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.unidade_federacao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_terreno_marinha TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_rodoviario_a TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_ltm TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.vegetacao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.utilizacao_a TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_energia_comunic TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_duto TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.localizacao_rffsa TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.alteracao_fisiografica_antropica_l TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.alteracao_fisiografica_antropica_p TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.area_especial TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.area_identificacao_direta TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.assentamento_precario TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.bairro TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.canal_vala_a TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ponto_cotado_altimetrico TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ponto_cotado_batimetrico TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_drenagem TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_arruamento_l TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.localidade TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ponto_energia_comunic TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pto_geod_topo_controle TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.setor_censitario TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.terreno_cadastral TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_ferroviario TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_lpm TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_arruamento_a TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.massa_dagua TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_tagp TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.est_gerad_energia_l TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.alteracao_fisiografica_antropica_a TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_rodoviario_l TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_lmeo TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trecho_terreno_acrescido_marginal TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.linha_praia TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.localizacao_imovel TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.mobiliario_urbano TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.metadado_produto_cartografico TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.canal_vala_l TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.complementar_a TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.complementar_p TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.curva_batimetrica TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.curva_nivel TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.distrito TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.edificacao_a TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.edificacao_p TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.elemento_fisiografico_a TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.elemento_fisiografico_l TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.estacao_ferroviaria TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.est_gerad_energia_a TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.est_gerad_energia_p TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.estrut_apoio_transporte_a TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.estrut_apoio_transporte_p TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.faixa_dominio TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.faixa_fronteira TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.faixa_seguranca TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ilha TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.limite_mar_territorial TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.linha_costa TO zago;


select 'GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON '|| schemaname||'.'||tablename || ' TO zago;'  
from pg_tables where schemaname = 'externo'

GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.grid_colecao_96 TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo."92_trecho_riojaneiro_recreio" TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.colecoeshistoricas TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.faces_logradouro TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo."64_trecho_riojaneiro_centro" TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo."91_trecho_riojaneiro_barra" TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.vegetacao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo."62_trecho_cabofriocanaitajuru_fortesaomateus-canalpalmer" TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.grid_colecao_93 TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.grid_colecao_94 TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.trecho_terreno_acrescido_marinha TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.trecho_terreno_marinha TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.linha_costa TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.grid_colecao_95 TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.massa_dagua TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.terreno_sujeito_inundacao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.trecho_lpm TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER, REFERENCES, TRUNCATE ON externo.trecho_ltm TO zago;

select 'GRANT SELECT, INSERT, UPDATE, DELETE ON '|| schemaname||'.'||tablename || ' TO zago;'  
from pg_tables where schemaname = 'dominio'

GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.situacao_espacial TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.administracao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.posicao_relativa TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.referencial_altim TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.regime TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_elem_nat TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_est_apoio_transporte TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_est_gerad TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_faixa_seguranca TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_ilha TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_localidade TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_massa_dagua TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_mobiliario TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_ponto TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_ponto_enc TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_ponto_energia_comunic TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_pto_ref_geod_topo TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_ref TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.auxiliar TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.bitola TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.causa_exposicao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.classificacao_porte TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.demanda_geradora TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.densidade TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.especie_trecho_energia TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_trecho_comunic TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_trecho_drenagem TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_trecho_duto TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.mat_constr TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.mat_transp TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.metodologia_lmeo TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.modal_uso TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.modalidade TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.nr_linhas TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.nivel_precisao_cartografia TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.nivel_precisao_imovel TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.posicao_rel_edific TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.revestimento TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.setor TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.sigla_uf TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.sistema_geodesico TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.situacao_fisica TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.situacao_juridica TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.etapa_demarcacao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_torre TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_assentamento_precario TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_benfeitoria TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_complementar TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_curva_nivel TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_logradouro TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.situacao_trecho TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_area_especial TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.jurisdicao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.mat_condutor TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.finalidade_galeria_bueiro TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_superficie TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_terreno_exposto TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_trecho TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_vegetacao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_via TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.trafego TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.uso_principal TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.dominio_uniao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_identificacao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_alter_antrop TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_pavimentacao TO zago;
GRANT SELECT, INSERT, UPDATE, DELETE ON dominio.tipo_trecho_ferrov TO zago;
commit;